int** init(int scale);
void run();
int up();
int left();
int right();
int down();
void print();
int addnew();
void clean();
void addhelper();
void color(int num);
char nextCommand();
int isFull(int col);
int setPrimary();