# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baitter_Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
