# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Baitter_Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('vericode', models.CharField(max_length=255, null=True)),
                ('following', models.ManyToManyField(to='Baitter_User.User')),
                ('liked', models.ManyToManyField(related_name='Liked', to='Baitter_Post.Post')),
                ('posted', models.ManyToManyField(related_name='Posted', to='Baitter_Post.Post')),
            ],
            options={
                'db_table': 'USERS',
                'ordering': ['u_id'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
