# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baitter_User', '0002_auto_20180422_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
