# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github Portfolio' do
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.3'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Github Portfolio

  target 'Github PortfolioTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
